# Generated by Django 4.0.4 on 2022-04-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='win_type',
            new_name='win',
        ),
        migrations.AlterField(
            model_name='winner',
            name='date',
            field=models.DateField(verbose_name='win date'),
        ),
    ]
