# Generated by Django 4.0.4 on 2022-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_win_type_winner_win_alter_winner_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='game',
            name='kit',
            field=models.ManyToManyField(to='main_app.kit'),
        ),
    ]
